DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INT CHECK ( age < 100 )
);

CREATE TABLE Item
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id INT          REFERENCES Person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);


DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS Principal;

CREATE TABLE Principal
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age  int CHECK (age > 18)
);

CREATE TABLE School
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_number int        NOT NULL,
    principal_id  int UNIQUE REFERENCES Principal (id) ON DELETE SET NULL
);


DROP TABLE IF EXISTS Movie;
DROP TABLE IF EXISTS Director;

CREATE TABLE Director
(
    director_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(100) NOT NULL UNIQUE,
    age         int CHECK (age > 10)
);


CREATE TABLE Movie
(
    movie_id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_id        int          NOT NULL REFERENCES director (director_id),
    name               varchar(200) NOT NULL,
    year_of_production int CHECK (year_of_production > 1900)
);