CREATE TABLE Person(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL ,
                       age INT,
                       email VARCHAR(100)
);